const movies = [
    {
        poster: './assets/movie2.png',
        title: 'Red Notice',
        director: 'Rawson Marshall Thurber',
        writter: 'Rawson Marshall Thurber',
        cinematography: 'Markus Forderer',
        production: 'Flynn Picture Company Seven Bucks Productions Bad Version, Inc.',
        released: '(2021)',
        duration: '118 Min.',
        producers: 'Beau Flynn, Dany Garcia, Hiram Garcia',
        aired: 'November 12, 2021',
        distributor: 'Netflix',
        rate: '0.00',
        scores: [],
        genre: ['Action', 'Comedy', 'Thriller'],
        country: 'United States',
        language: 'English',
        rating: 'PG-13',
        p1: 'An Interpol agent successfully tracks down the world\'s most wanted art thief, with help from a rival thief. But nothing is as it seems, as a series of double-crosses ensue.',
        p2: 'When an Interpol-issued Red Notice the highest level warrant to hunt and capture the world\'s most wanted goes out, the FBI\'s top profiler John Hartley (Dwayne Johnson) is on the case. His global pursuit finds him smack dab in the middle of a daring heist where he\'s forced to partner with the world\'s greatest art thief Nolan Booth (Ryan Reynolds) in order to catch the world\'s most wanted art thief, "The Bishop" (Gal Gadot). The high-flying adventure that ensues takes the trio around the world, across the dance floor, trapped in a secluded prison, into the jungle and, worst of all for them, constantly into each other\'s company.'
    },
    {
        poster: './assets/movie9.png',
        title: 'Spiderman: No Way Home',
        director: 'Jon Watts',
        writter: 'Chris McKenna, Erik Sommers',
        cinematography: 'Mauro Fiore',
        production: 'Columbia Pictures, Marvel Studios, Pascal Pictures',
        released: '(2021)',
        duration: '148 Min.',
        producers: 'Kevin Feige, Amy Pascal',
        aired: 'December 15, 2021',
        distributor: 'Sony Pictures Releasing',
        rate: '8.30',
        scores: [8.30],
        genre: ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'],
        country: 'United States',
        language: 'English',
        rating: 'PG-13',
        p1: 'Spider-Man No Way Home mengisahkan tentang kegelisahan Peter Parker yang diperankan Tom Holland karena difitnah.Siapa pemfitnahnya? ialah Mysterio (Jake Gyllenhaal) yang malah mati duluan sebelum masalah bisa diluruskan.Mysterio memang sudah meninggal, akan tetapi fitnah yang dilempar ke publik berkembang menjadi banyak spekulasi yang tudingan kepada Peter Parker.Berita tentang tudingan demi tudingan tentang Parker yang identitasnya telah terbongkar tersebut kian memanas karena adanya campur tangan koran The Daily Bugle yang dipimpin J Jonah Jameson (JK Simmons).Dalam sebuah berita yang diterbitkan, Spider-Man alias Peter Parker ini difitnah menjadi dalang pembunuhan Mysterio.Karena hal ini, Parker tak lagi punya privasi. Rumahnya selalu menjadi objek amatan masyarakat dan media. Kondisi tersebut membuat Peter Parker tersudutkan. Secara tidak langsung, rumor tersebut pun mempengaruhi hubungan Peter dengan MJ (Zendaya) yang baru berusia seumur jagung.',
        p2: 'Peter Parker gamang dan membuka pintu lintas semesta Karena tidak kuat menahan cemoohan-cemoohan sendirian, Parker pun mulai mencari ide untuk bisa meluruskan rumor tak sedap yang berkembang. Ia mendatangi Doctor Strange yang pernah sama-sama berjuang melawan Thanos. Ia meminta kepada Doctor Strange agar membuat masyarakat lupa jika dirinya adalah Spider-Man. Strange (Benedict Cumberbatch) sebenarnya sempat diberi peringatan oleh Wong (Benedict Wong), tapi ia tetap memilih membantu Peter Parker. Ketika Strange mulai merapal mantra, Parker malah berulah. Ia berubah pikiran. Hal tersebut membuat Strange marah dan malah salah dalam merapal mantra. Kesalahan ini membuat batas lintas-semesta menjadi terbuka dan menarik sejumlah pihak dari semesta lain masuk dalam semesta yang saat ini dihuni Peter dan Strange. Dan benar saja, mahluk-mahluk tersebut memburu Peter Parker. Padahal, Peter Parker yang ada di dunia ini bukanlah yang mereka kenal. Doctor Strange memerintahkan Parker mengumpulkan mahluk-mahluk tersebut untuk nantinya dikembalikan ke alam asli mereka. Namun ada saja tantangan yang harus dihadapi.'
    },
    {
        poster: './assets/image 2.png',
        title: 'Morbius',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '108 Min.',
        producers: 'Avi Arad, Emma Ludbrook, Matt Tolmach, Lucas Foster',
        aired: 'March 30, 2022',
        distributor: '',
        rate: '5.20',
        scores: [5.20],
        genre: ['Action', 'Horror'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Film Morbius berpusat di sekitar karakter Dr. Michael Morbius, ahli biologi dan biokimia Yunani yang menderita penyakit darah langka. Dia mencoba obat berbahaya yang justru mengubahnya jadi seperti vampir.Saat bepergian ke New York, Morbius berusaha menemukan obat untuk penyakit langka yang dideritanya seumur hidup. Untuk melakukan itu, Morbius bereksperimen dengan pengobatan radikal yang melibatkan DNA kelelawar vampir dan terapi kejut listrik.',
        p2: 'Alih-alih sembuh, Morbius malah menderita penyakit yang jauh lebih buruk, membuatnya haus darah seperti vampir. Namun dia juga mendapatkan kemampuan persis makhluk supernatural tersebut.'
    },
    {
        poster: './assets/image 4.png',
        title: 'Venom',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '108 Min.',
        producers: 'Avi Arad, Emma Ludbrook, Matt Tolmach, Lucas Foster',
        aired: 'March 30, 2022',
        distributor: '',
        rate: '5.20',
        scores: [5.20],
        genre: ['Action', 'Horror'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Film Morbius berpusat di sekitar karakter Dr. Michael Morbius, ahli biologi dan biokimia Yunani yang menderita penyakit darah langka. Dia mencoba obat berbahaya yang justru mengubahnya jadi seperti vampir.Saat bepergian ke New York, Morbius berusaha menemukan obat untuk penyakit langka yang dideritanya seumur hidup. Untuk melakukan itu, Morbius bereksperimen dengan pengobatan radikal yang melibatkan DNA kelelawar vampir dan terapi kejut listrik.',
        p2: 'Alih-alih sembuh, Morbius malah menderita penyakit yang jauh lebih buruk, membuatnya haus darah seperti vampir. Namun dia juga mendapatkan kemampuan persis makhluk supernatural tersebut.'
    },
    {
        poster: './assets/image 5.png',
        title: 'Uncharted',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '116 Min.',
        producers: 'Charles Roven, Avi Arad, Alex Gartner, Arthur Marcum, Ari Arad',
        aired: 'February 16, 2022',
        distributor: '',
        rate: '6.40',
        scores: [6.40],
        genre: ['Action'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Uncharted menceritakan dua saudara kandung, Nathan dan Sam Drake yang ditangkap karena mencuri peta pertama yang dibuat setelah ekspedisi Magellan.Sam berhasil melarikan diri, tetapi Nathan dikembalikan ke panti asuhan mereka. Sebelum berpisah, Sam memberikan cincin milik leluhur mereka kepada Nathan. Ia juga berjanji akan kembali.Lima belas tahun kemudian, Nathan (Tom Holland) bekerja sebagai bartender sekaligus pencopet.Ia lalu bertemu Victor \'Sully\' Sullivan (Mark Wahlberg) yang sempat bekerja sama dengan Sam dalam mencari harta karun yang disembunyikan kru Magellan.Sully menjelaskan kepada Nathan bahwa Sam menghilang saat membantunya mencuri buku harian Juan Sebastian Elcano. Nathan lalu setuju bergabung dengan Sully untuk mencari harta karun sekaligus menemukan saudaranya. Nathan dan Sully memulai perjalanan dengan mencuri salib emas yang terkait dengan kru Magellan.',
        p2: 'Namun mereka harus berhadapan dengan Santiago Moncada keturunan terakhir keluarga Moncada dan Jo Braddock, tentara yang disewa keluarga Moncada Nathan dan Sully lalu melanjutkan perjalanan Barcelona, tempat harta karun itu seharusnya disembunyikan. Namun Nathan menemukan peta yang menunjukkan bahwa harta karun itu berada di Filipina. Nathan dan Sully kembali melanjutkan perjalanan untuk mencari harta karun, tetapi mereka kembali diganggu oleh Braddock.'
    },
    {
        poster: './assets/image 6.png',
        title: 'Doctor Strange in the Multiverse of Madness',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '126 Min.',
        producers: 'Kevin Feige',
        aired: 'May 5, 2022',
        distributor: '',
        rate: '7.30',
        scores: [7.30],
        genre: ['Action', 'Horror'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Doctor Strange 2 mengisahkan perjuangan Stephen Strange (Benedict Cumberbatch) menghadapi berbagai kejadian aneh akibat pintu lintas semesta yang terbuka pasca kejadian di Spider-Man No Way Home. Hal itu dimulai ketika Strange mengalami serangkaian penglihatan saat dirinya tidur. Dalam penglihatan tersebut, sosok yang mirip dirinya tengah berusaha kabur dan melawan monster di sebuah semesta yang aneh. Ia tak sendiri. Sosok serupa Strange itu bersama dengan seorang gadis dan mereka berusaha melewati berbagai pijakan yang berpindah-pindah untuk menghindari monster tersebut. Ketika di penghujung jalan, mereka menemukan sebuah altar dengan tiang pendek di tengahnya yang bersinar. Di sana, terdapat benda mirip The Book of Vishanti.',
        p2: 'Strange berusaha untuk menggapai buku itu demi bisa mengalahkan monster dan keluar dari semesta itu. Namun di sisi lain, Strange juga harus melindungi gadis yang bersamanya agar si monster tidak memiliki kekuatan perempuan itu. Ia pun terlibat dalam pertarungan sengit, hingga akhirnya ketika mereka semua terpojok, gadis tersebut mengeluarkan kekuatan besar dan cahaya putih yang menyilaukan. Stephen Strange pun terbangun dari tidurnya.'
    },
    {
        poster: './assets/image 15.png',
        title: 'Avengers: Endgame',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2019)',
        duration: '181 Min.',
        producers: 'Kevin Feige',
        aired: 'April 24, 2019',
        distributor: '',
        rate: '8.40',
        scores: [8.40],
        genre: ['Action'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Setelah peristiwa yang memusnahkan setengah dari populasi Bumi di Avengers: Infinity War (2018), kisah akan berlanjut saat Avengers yang tersisa berkumpul sekali lagi untuk melawan Thanos (Josh Brolin). Namun Kesedihan, keputusasaan dan ketidakberdayaan masih tetap menyelimuti para pahlawan super. Trailer Avengers: Endgame didominasi potret "kehancuran" di bumi usai Thanos memusnahkan separuh populasi dunia. Warna hitam putih mendominasi cuplikan film besutan Joe dan Anthony Russo tersebut. Dalam sinopsis Avengers: Endgame, para Avengers pun berusaha untuk memulihkan tatanan alam semesta.',
        p2: 'Avengers yang tersisa seperti Steve Rogers/Captain America (Chris Evans), Natasha Romanoff/Black Widow (Scarlett Johansson) hingga Thor (Chris Hemsworth) mendapat bantuan dari Carol Danvers/Captain Marvel (Brie Larson). Hawkeye (Jeremy Renner) yang tak hadir saat Infinity War juga bakal tampil di Avengers: Endgame dengan busur dan panah andalannya. Scott Lang/Ant-Man (Paul Rudd) pun hadir membantu para Avengers yang tersisa untuk melawan Thanos.Marvel Studio bakal menghadirkan pertarungan Avengers melawan Thanos selama tiga jam. Dikutip dari Hollywood Reporter, durasi tersebut menjadikannya sebagai film superhero terpanjang yang diproduksi Marvel Cinematic Universe (MCU). Sayangnya, Avengers: Endgame akan menjadi cameo terakhir bagi pencipta para superhero, Stan Lee. Hal ini diungkapkan sutradara Endgame, Joe Russo. Endgame dianggap sebagai film yang pas untuk jadi cameo terakhir Lee. "Aku meyakini cameo terakhir Lee adalah Endgame," kata Russo.'
    },
    {
        poster: './assets/image 20.png',
        title: 'KKN Di Desa Penari',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '140 Min.',
        producers: 'Manoj Punjabi',
        aired: 'April 30, 2022',
        distributor: '',
        rate: '6.30',
        scores: [6.30],
        genre: ['Horror'],
        country: '',
        language: 'Indonesia',
        rating: 'PG-13',
        p1: 'Film ini diangkat dari cerita seseorang yang dibagikan melalui Twitter oleh akun Simple Man pada 2109 silam. Diceritakan banyak kejadian mistis yang dialami sekelompok mahasiswa ketika melaksanakan Kuliah Kerja Nyata (KKN) di sebuah desa terpencil bernama Desa Penari.Keenam mahasiswa itu bernama Nur diperankan Tissa Biani, Widya (Adinda Thomas), Ayu (Aghniny Haque), Bima (Achmad Megantara), Anton (Calvin Jeremy), dan Wahyu (Fajar Nugraha). Dikisahkan dalam film, kegiatan yang mereka awalnya berjalan dengan lancar. Namun, lama-kelamaan sejumlah kejadian mistis pun muncul.Dimulai oleh Nur yang merasa ketakutan akan hal mistis, ditambah lagi Widya kesurupan menari.',
        p2: 'Teror selanjutnya kemudian dirasakan anggota kelompok yang lain, misalnya Bima melakukan hal aneh. Dia pergi diam-diam meninggalkan penginapan dan Ayu tidak bisa berhenti menari. Di suatu waktu, Nur kesurupan roh seorang nenek yang mengatakan bahwa salah satu dari mereka ada yang melanggar aturan desa tersebut. Serentetan pengalaman horor tersebut menghantui mereka hingga program KKN itu berakhir tragis.'
    },
    {
        poster: './assets/image 12.png',
        title: 'Avengers: Infinity War',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2018)',
        duration: '149 Min.',
        producers: 'Kevin Feige',
        aired: 'April 25, 2018',
        distributor: '',
        rate: '8.00',
        scores: [8.00],
        genre: ['Action'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Thanos (Josh Brolin) berambisi untuk mengumpulkan enam batu abadi yang tersebar di berbagai tempat. Setiap batu memiliki kekuatan tersendiri sehingga tidak sembarang orang bisa mendapatkannya. Jika sudah memiliki keenam batu abadi, Thanos bisa menjadi penguasa semesta. Thanos pun berniat menghilangkan separuh populasi semesta karena dipercaya bisa membuat kehidupan lebih sejahtera. Thanos bersama anak buahnya menebar teror sambil mencari batu-batu tersebut. Kekejaman Thanos disaksikan sendiri oleh Bruce Banner/Hulk (Mark Ruffalo) dan Thor (Chris Hemsworth). Mereka berniat menemukan superhero lain agar bisa mencegah ambisi Thanos. Hulk kembali ke bumi dan memberi tahu aksi Thanos kepada Tony Stark/Iron Man (Robert Downey Jr.), Doctor Strange (Benedict Cumberbatch) serta Wong (Benedict Wong). Sialnya, Thanos sudah muncul sebelum mereka bertindak lebih jauh. Alhasil Iron Man dan Doctor Strange masuk kapal luar angkasa Thanos. Kekacauan bertambah ketika Peter Parker/Spider-Man (Tom Holland) ikut terbawa mereka.',
        p2: 'Sementara Thor diselamatkan anggota Guardians of the Galaxy. Thor percaya hanya bisa menyelamatkan Thanos dengan bantuan palu sakti miliknya. Bersama Rocket (pengisi suara Bradley Cooper) dan Groot (pengisi suara Vin Diesel), Thor pergi ke planet lain untuk mendapatkan palu sakti baru.Saat Thor dan Hulk menyusun rencana, anak buah Thanos mengincar Vision (Paul Bettany). Salah satu batu abadi berada dalam tubuh Vision. Sadar nyawa pacarnya terancam, Wanda Maximoff/Scarlet Witch (Elizabeth Olsen) meminta bantuan Steve Rogers/Captain America (Chris Evans), Natasha Romanoff/Black Widow (Scarlett Johansson), dan Sam Wilson/Falcon (Anthony Mackie). Captain America kemudian membawa mereka ke Wakanda dan bertemu TChalla/Black Panther (Chadwick Boseman) serta Bucky Barnes/Winter Soldier (Sebastian Stan). Captain America merasa Wakanda merupakan tempat yang aman. Wakanda juga memiliki pasukan memadai sehingga mampu menghadapi perang. Lantas dimana Thanos? Sang penjahat tengah memaksa putri tirinya, Gamora (Zoe Saldana) untuk menunjukan letak salah satu batu abadi. Ini membuat Peter Quill/Star-Lord (Chris Pratt), Drax (Dave Bautista), dan Mantis (Pom Klementieff) bertekad menyelamatkannya.'
    },
    {
        poster: './assets/image 26.png',
        title: 'Black Panther',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2018)',
        duration: '135 Min.',
        producers: 'Kevin Feige, David J. Grant',
        aired: 'February 14, 2018',
        distributor: '',
        rate: '7.30',
        scores: [7.30],
        genre: ['Action'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'BLACK PANTHER mengisahkan tentang Raja TChalla yang kembali ke Wakanda setelah peristiwa yang terjadi dalam film CAPTAIN AMERICA: CIVIL WAR dimana sang ayah, TChaka tewas. Namun, kembalinya TChalla sebagai penguasa ini ditentang oleh sebuah kelompok. Salah satunya Erik Killmonger yang berusaha merebut tahta TChalla dan menguasai Wakanda.',
        p2: 'Saat para musuh berusaha untuk menjatuhkan kekuasaannya, TChalla sang Black Panther juga dibantu sang adik yaitu Shuri. Lantas, mampukah sang Black Panther mempertahankan tahtanya? Sebagai film superhero Marvel yang sangat berbeda dari sebelumnya, BLACK PANTHER merupakan sebuah tontonan bergenre sci-fi yang sangat direkomendasikan untuk para pecinta film. Selain di Atlanta, Korea Selatan juga dipilih jadi salah satu tempat syuting film itu.'
    },
    {
        poster: './assets/image 17.png',
        title: 'Iron Man 3',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2013)',
        duration: '130 Min.',
        producers: 'Kevin Feige',
        aired: 'April 25, 2013',
        distributor: '',
        rate: '7.10',
        scores: [7.10],
        genre: ['Action'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Seperti yang diketahui Tony Stark adalah seorang pengusaha sukses sekaligus merangkap menjadi Iron Man, seorang pahlawan super yang terkenal dengan baju besinya.Diawali flashback menuju tahun 1999, di mana Tony bertemu temannya, Maya Hansen (Rebecca Hall), yang merupakan seorang Botanis di Bern, Switzerland.Ia juga bertemu dengan seorang ilmuwan gila dan arogan bernama Aldrich Killian (Guy Pearce).Saat itu Aldrich sedang mengembangkan sebuah proyek bernama Advanced Idea Mechanics.Proyek ini akan mengembangkan DNA manusia agar dapat berubah drastis dan menyembuhkan berbagai penyakit.Cerita kemudian kembali lagi ke New York City pada tahun 2012.Tony Stark sedang mengalami sindrom traumatik setelah bertempur bersama Avengers melawan Loki, adik dari Thor.Tony pun mulai merasa tak aman dan memutuskan ia harus mengembangkan robot-robot Iron Man-nya.Tony Stark kemudian membuat beberapa baju Iron Man baru di dalam tempat tinggalnya, serta mencoba mengembangkan model baru bernama Mark 42.Model baru Iron Man ini dapat terbang menjemputnya dengan bagian-bagian terpisah.Namun rupanya Tony Stark belum dapat menemukan cara yang tepat untuk membuat MK42 yang sempurna.Narasi Tony Stark kembali berlanjut di mana ia menceritakan tentang seorang penjahat baru yang muncul bernama The Mandarin (Ben Kingsley).',
        p2: 'The Mandarin diceritakan telah membajak pesawat Amerika Serikat serta menjadi pelaku dari pengeboman markas militer Amerika Serikat di Kuwait yang kemudian membunuh para istri serta anak-anak dari tentara.Kisah terus berlanjut hingga seorang bawahan baru Tony Stark, Happy Hogan (Jon Favreau) yang mengalami kecelakaan pada pengeboman Grauman’s Chinese Theater setelah menginvestigasi anak buah Killian, yang sebelumnya meminta bantuan Tony untuk proyek AIM-nya namun ditolak.Tony kemudian menemukan sebuah keganjalan di TKP yang membawanya menuju jawaban tentang proyek Killian yang misterius.Tak lama setelah itu, Tony mendapat kunjungan dari teman Botanisnya, Maya, yang memperingatkan Tony kalau ia sedang dalam bahaya.Benar saja, kunjungan Maya pun berakhir dengan diserangnya rumah Tony dan memaksa Tony untuk kabur menggunakan baju Iron Man-nya.Pingsan di sepanjang perjalanan, Tony terbangun karena mendengar peringatan bateri lemah dari Jarvis.Ia akhirnya terdampar di Tennessee, sebuah kota yang sangat jauh dari New York City.Di sana ia bertemu dengan seorang anak kecil, Harley Keener (Ty Simpkins) di mana Tony menumpang di rumahnya dan menemukan cara untuk dapat kembali dan melawan The Mandarin.Ditemani oleh Harley dan peralatan rumahan yang dimilikinya, Tony pun harus berusaha untuk dapat mengaktifkan kembali baju Iron Man dan Jarvis yang tengah mati.Dirinya menghubungi Pepper Potts (Gwyneth Paltrow), sekaligus mempersiapkan diri tanpa robot-robot Iron Man-nya untuk melawan The Mandarin.'
    },
    {
        poster: './assets/movie4.png',
        title: 'The Contractor',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '103 Min.',
        producers: 'Basil Iwanyk, Erica Li, Erica Lee',
        aired: 'April 8, 2022',
        distributor: '',
        rate: '5.00',
        scores: [5.00],
        genre: ['Action'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'film The Contractor berkisah tentang James Harper, seorang tentara Amerika Serikat yang dipaksa mundur karena kondisi kesehatannya. Padahal, James sedang membutuhkan uang untuk kebutuhan keluarganya. Di tengah kebingungannya mencari uang, James bertemu dengan temannya yang juga merupakan veteran, bernama Mike.Mike kemudian mengajak James untuk bergabung ke organisasi militer swasta yang memberikan gaji cukup besar. Tergiur dengan bayarannya, James setuju dan Mike mengajak James menemui pemimpin organisasi bernama Rusty Jennings, yang juga merupakan veteran.',
        p2: 'Rusty kemudian mengutus James dan Mike untuk menjalankan misi di Jerman.James ditugaskan untuk mengawasi seorang ilmuwan bernama Salim Mohamed Mohsin. Awalnya, misi ini berjalan dengan baik dan terasa normal. Semakin lama menjalaninya, James menemukan banyak kejanggalan pada misi yang dia jalani. Dengan berbagai keanehan yang dia temui, apakah James sanggup menyelesaikan misinya?'
    },
    {
        poster: './assets/movie6.png',
        title: 'No Time To Die',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2021)',
        duration: '163 Min.',
        producers: 'Michael G. Wilson, Barbara Broccoli',
        aired: 'September 30, 2021',
        distributor: '',
        rate: '8.00',
        scores: [8.00],
        genre: ['Action'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'James Bond (Daniel Craig) menjalani kehidupan seperti manusia biasa setelah memutuskan pensiun dari MI6. Ia tak lagi menjadi andalan atau menyandang status agen spionase dengan kode 007.Kini Bond kerap menghabiskan waktu sehari-hari dengan kekasihnya, Madeleine Swann (Lea Seydoux). Mereka hidup bahagia, terlebih ketika berlibur ke kota Matera, Basilicata, Italia.Liburan itu menjadi petaka ketika Bond diserang Specter, organisasi yang ia lawan dalam beberapa tahun terakhir. Ia menduga Swan terlibat dalam serangan itu karena hanya dia yang mengetahui keberadaannya.Tanpa pikir panjang Bond langsung mengakhiri hubungannya dengan Swan.',
        p2: 'Ia bahkan menyatakan tidak ingin bertemu lagi meski Swan berharap bisa bertemu kembali dengannya di kemudian hari.Kehidupan Bond mendadak sepi. Ia kemudian pindah ke Jamaika dan selama lima tahun tidak menjalin hubungan dengan siapa pun karena sebenarnya memang masih mencintai Swan.Seketika Bond dihampiri oleh Felix Leiter (Jeffery Wright), temannya sekaligus agen CIA. Ia meminta bantuan kepada Bond untuk menyelesaikan sebuah misi di Kuba yang berkaitan dengan Spectre.Sejak saat itu ia kembali beraksi sebagai spionase. Misi itu membuat Bond bingung karena ada sosok dan organisasi lain di balik Spectre yang berkuasa. Organisasi yang dipimpin Lyutsifer Safin (Rami Malek) itu bahkan memiliki senjata biologi yang sangat mematikan.'
    },
    {
        poster: './assets/movie7 1.png',
        title: 'Scream',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '104 Min.',
        producers: 'James Vanderbilt, William Sherak, Paul Neinstein',
        aired: 'January 12, 2022',
        distributor: '',
        rate: '7.00',
        scores: [7.00],
        genre: ['Horror'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Sudah setengah abad berlalu, Billy Loomis dan Stu Macher sebagai Ghostface menyerang kota Woodsbro. Lalu, beberapa anggota lainnya menyerang siswi SMA, Tara Carpenter (Jenna Ortega) yang saat itu sedang sendiri di rumah. Ia terluka parah, tapi masih bisa bertahan hidup.Kemudian, sang kakak, Sam Carpenter (Melissa Barrera), datang menemui Tara di rumah sakit bersama kekasihnya, Richie (Jack Quaid). Ia juga bertemu dengan teman-teman Tara yang sudah lama tidak saling berkomunikasi. Beberapa jam usai menjenguk, Sam diserang oleh Ghostface.Sam dihantui halusinasi Billy Loomis (Skeet Ulrich) yang suatu saat terungkap merupakan ayah biologisnya. Ditambah bayang-bayang alasan ia meninggalkan kota, mengasingkan diri, serta membiarkan adiknya tinggal sendiri di Woodsbro.Usai dua kasus tersebut, penyerangan terus-terusan terjadi hingga menghabisi nyawa teman-teman Sam dan Tara. Mereka diperingatkan oleh Amber (Mikey Madison) untuk melawan Ghostface, namun Sam memilih melarikan diri karena lelah berurusan dengan pembunuh tersebut.',
        p2: 'Amber kemudian mengikuti keduanya dan menghentikan langkah kakak beradik tersebut. Ia menyerang Sam dengan mengaku sebagai anggota Ghostface. Lalu, ia meminta Sam untuk menyatakan diri bahwa dirinya juga adalah kaki tangan kelompok tersebut. Di sinilah situasi semakin rumit dan menegangkan, sehingga dianggap sebuah klimaks oleh para pengamat dan penonton.Apa yang sebenarnya terjadi? Siapa anggota Ghostface yang sekarang kembali menyerang kota Woodsbro? Bagaimana nasib Sam dan Tara selanjutnya? Lalu, apakah benar Billy adalah ayah kandung dari kakak beradik ini?'
    },
    {
        poster: './assets/movie8 1.png',
        title: 'Eternals',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2021)',
        duration: '156 Min.',
        producers: 'Kevin Feige, Nate Moore',
        aired: 'November 3, 2021',
        distributor: '',
        rate: '7.00',
        scores: [7.00],
        genre: ['Action', 'Fantasy'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Dalam trailer Eternals, kita diingatkan akan perbuatan Thanos yang telah memusnahkan setengah populasi di semesta.Namun manusia yang ada di Bumi mengembalikan setiap orang dengan cara menjentikkan jari.Kembalinya populasi secara tiba-tiba memberikan energi yang diperlukan untuk memulai kemunculan.Dan mereka hanya punya waktu 7 hari Marvel Studios Eternals menampilkan tim Pahlawan Super baru yang menarik, alien kuno yang telah hidup di Bumi secara rahasia selama ribuan tahun.',
        p2: 'Pahlawan Super baru itu pernah datang 7.000 tahun yang lalu untuk melindungi manusia dari Deviants.Mengapa mereka tidak membantu melawan Thanos? Mereka diinstruksikan untuk tidak ikut campur konflik manusia, kecuali berhubungan dengan Deviants.Ada kalimat yang menjadi sorotan di trailer ini, yakni "When you love something, you protect it".Dalam bahasa Indonesia berarti "Ketika kamu mencintai sesuatu, kamu melindunginya".Lantas, siapa dalang di balik peristiwa itu?Dan bagaimana Pahlawan Super baru ini melindungi semesta?'
    },
    {
        poster: './assets/image 4.png',
        title: 'Venom: Let There Be Carnage',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2021)',
        duration: '156 Min.',
        producers: 'Tom Hardy, Kelly Marcel, Amy Pascal, Avi Arad, Hutch Parker, Matt Tolmach',
        aired: 'November 17, 2021',
        distributor: '',
        rate: '7.00',
        scores: [7.00],
        genre: ['Action', 'Fantasy'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Venom: Let There Be Carnage mengisahkan pertarungan sengit antara Venom dengan Carnage yang menempel di tubuh pembunuh berantai bernama Cletus Kasady. Berikut sinopsis Venom 2: Let There Be Carnage.Venom 2: Let There Be Carnage masih melanjutkan aksi Eddie Brock (Tom Hardy) seorang jurnalis yang berubah menjadi karakter jahat bernama Venom usai terpapar alien berbentuk cairan kental yang disebut symbiote.Setelah berhasil menghentikan Riot atau Carlton Drake (Riz Ahmed) di film sebelumnya, Eddie Brock berusaha menjalani hidup baru sebagai inang Venom yang dikenal haus memangsa otak manusia. Sebagai gantinya, Eddie menyediakan coklat dan organ hewan untuk dimangsa Venom.Suatu hari, Eddie didatangi seorang detektif bernama Patrick Mulligan (Stephen Graham) dan memintanya menemui Cletus Kasady (Woody Harrelson) seorang pembunuh berantai yang akan dihukum mati.Walau terpaksa, Eddie akhirnya menyanggupi permintaan tersebut.',
        p2: 'Usai bertemu Kasady, Eddie terpancing dengan goresan di dinding sel Kasady yang menyimpan misteri.Berkat bantuan Venom yang menempel di tubuhnya, Eddie berhasil memecahkan pesan rahasia tersebut. Rupanya, pesan itu berisi lokasi tempat Kasady menyimpan tubuh korban-korbannya.Setelah penemuan itu, Kasady kembali mengajukan satu permintaan terakhir untuk bertemu dengan Eddie. Di akhir perjumpaan mereka, Eddie membuat Kasady marah dan menggigit tangan Eddie sampai mengeluarkan darah.Kasady lalu dibawa ke ruang eksekusi. Namun hal aneh terjadi pada tubuh Kasady. Ia berubah menjadi symbiote berwarna merah dan menyebut dirinya sebagai Carnage.Kasady yang berubah menjadi Carnage menyerang petugas penjaga dan kabur dari penjara untuk mencari Eddie.'
    },
    {
        poster: './assets/movie11 1.png',
        title: 'Shang-Chi and the Legend of the Ten Rings',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2021)',
        duration: '132 Min.',
        producers: 'Kevin Feige, Jonathan Schwartz',
        aired: 'September 30, 2021',
        distributor: '',
        rate: '7.40',
        scores: [7.40],
        genre: ['Action', 'Fantasy'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Kisah Shang-Chi bermula dari legenda sepuluh gelang ajaib yang dimiliki oleh Xu Wenwu sejak ribuan tahun lalu. Gelang tersebut memiliki magis luar biasa dan memberikan kekuasaan juga kekuatan tak terhingga bagi pemegangnya.Berkat itu pula, Xu Wen Wu mendirikan organisasi Ten Rings dan menaklukkan banyak kerajaan, menyusup pemerintahan, dan menjalankan roda bisnis di berbagai wilayah di dunia selama bertahun-tahun.Hingga pada 1996, Xu Wenwu menemukan soal legenda desa ajaib Ta Lo. Menurut legenda, desa tersebut memiliki kekuatan yang lebih hebat dan Xu Wenwu berambisi untuk memilikinya.Akan tetapi, kala dirinya berusaha menemukan Ta Lo, ia justru bertemu seorang perempuan dan jatuh cinta kepadanya, Ying Li, seorang penjaga desa itu dan berhasil mengalahkan Xu Wen Wu.Singkat cerita, keduanya yang semula bertarung malah jatuh cinta pun memutuskan untuk bersama. Pernikahan mereka melahirkan dua anak, Xu Shang-Chi dan Xu Xialing. Xu Wenwu pun merasa tujuan hidupnya terpenuhi.Namun takdir berkata lain. Ying Li meninggal dunia dan mengubah karakter Xu Wenwu.',
        p2: 'Ia kemudian mendidik Xu Shang-Chi menjadi pembunuh kelas kakap sejak usia tujuh tahun. Xialing diam-diam mengikuti latihan yang diberikan kepada kakaknya itu.Pada Shang-Chi usia 14 tahun, ia diberi tugas untuk membunuh pemimpin Iron Gang. Namun setelah melaksanakan misi tersebut, Shang-Chi kabur dan memutuskan menjalani kehidupan baru dengan nama Shaun di San Fransisco.Di kota San Fransisco, Shaun tumbuh menjadi pemuda yang mampu 4 bahasa namun dirinya kini hanya menjadi petugas valet hotel bintang lima. Ia bekerja bersama sahabatnya sejak tiba di San Fransisco, Katy (Awkwafina).Keduanya amat menikmati kehidupan santai dan tanpa beban, meski sahabat dan keluarga Katy kerap mendorong mereka untuk mencari pekerjaan yang lebih baik. Namun mereka lebih gemar sebagai petugas valet dan karaoke.Hingga suatu hari, Shang-Chi mendapatkan sebuah kartu pos anonymous dengan sebuah alamat di Macau dan bergambar origami naga yang pernah dibuat ibunya kala ia masih anak-anak. Ia menganggap kartu pos itu dari adiknya yang lama tak berjumpa.Suatu kali, Shang-Chi dan Katy mendapatkan serangan dari segerombol orang tak dikenal kala mereka naik bus umum. Mereka ingin merebut kalung liontin Shang-Chi yang merupakan warisan Ying Li.'
    },
    {
        poster: './assets/movie12 1.png',
        title: 'yowis ben finale',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2021)',
        duration: '95 Min.',
        producers: 'Chand Parwez Servia, Fiaz Servia',
        aired: 'December 16, 2021',
        distributor: '',
        rate: '7.50',
        scores: [7.50],
        genre: ['Comedy'],
        country: '',
        language: 'Indonesia',
        rating: 'PG-13',
        p1: 'Yowis Ben Finale akan mengisahkan mengenai titik akhir dari empat personil band Yowis Ben, dan juga penyelesaian konflik dari empat tokoh tersebut. Salah satu konflik yang ada adalah bagaimana Bayu harus memilih di antara mantan kekasihnya (Cut Meyriska) atau gebetan, Asih (Anya Geraldine).',
        p2: 'Selain itu, Nando (Brandon Salim) juga tampak bimbang akan kepindahannya ke Amerika Serikat. Dalam film ini, Bayu Skak tidak hanya berakting saja, namun ia turut turun tangan dalam menyutradarai Yowis Ben Finale bersama dengan Fajar Nugros.  Bayu Skak berharap penutup dari tetralogi Yowis Ben ini dapat menutup kisah dengan manis dan menjadi kebanggaan masyarakat.'
    },
    {
        poster: './assets/movie13.png',
        title: 'Kambodja',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '76 Min.',
        producers: 'Frederica',
        aired: 'May 13, 2022',
        distributor: '',
        rate: '6.00',
        scores: [6.00],
        genre: ['Romance'],
        country: '',
        language: 'Indonesia',
        rating: 'PG-13',
        p1: 'Film Kambodja akan menceritakan konflik rumah tangga dan perselingkuhan yang terjadi dalam rumah kosan antara dua pasangan suami istri.Berlatar di tahun 1955 di Jakarta, terdapat sepasang suami istri bernama Danti (Della Dartyan) dan Sena (Revaldo), yang tinggal di sebuah indekos.Indekos adalah semacam rumah kos yang dimiliki Cik Mei dan memiliki tiga kamar di dalamnya.Danti merupakan seorang pekerja di perpustakaan, dan Sena aktif dalam sebuah partai politik.Kamar pertama dihuni oleh Bayu (Adipati Dolken) dan istrinya, Lastri (Carmela van der Kruk).Bayu sendiri adalah seorang penulis lepas kolom opini dan cerita pendek di surat kabar, sedangkan Lastri merupakan seorang biduan.Danti dan Sena menghuni kamar kedua, sedangkan kamar lainnya disewa oleh seseorang bernama Erwan.',
        p2: 'Indekos tersebut mulai terasa sepi ketika Sena harus pergi ke luar Kota untuk urusan partai, dan Lastri keliling kota untuk bernyanyi di acara kampanye suatu partai.Di samping itu, Danti dan Bayu nyaris tidak pernah bercakap. Setiap kali berpapasan, keduanya hanya menyapa dengan senyuman.Ketika sedang menunggu bis umum, mereka berteduh di bawah pohon Kamboja dan bercakap untuk yang pertama kalinya.Hidup keduanya terasa membosankan. Danti yang selalu menunggu Sena pulang, dan Bayu yang selalu ditinggal Lastri.Setelah perbincangan di bawah pohon Kamboja itu tanpa sadar membuat Bayu dan Danti mulai dekat, apalagi keduanya punya nasib yang sama.Suatu hari, Danti dan Bayu mendapati Istri dan suami mereka masing-masing menyimpan tiket perjalanan dari Surabaya yang sama persis.Mengetahui hal itu, mereka sadar bahwa mereka baru saja menguak kisah tentang perselingkuhan Sena dan Lastri.'
    },
    {
        poster: './assets/movie14 1.png',
        title: 'Jujutsu Kaisen 0',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '105 Min.',
        producers: 'MAPPA',
        aired: 'March 16, 2022',
        distributor: '',
        rate: '8.50',
        scores: [8.50],
        genre: ['Anime', 'Horror', 'Action'],
        country: '',
        language: 'Japanese',
        rating: 'PG-13',
        p1: 'Jujutsu Kaisen 0 berfokus pada karakter protagonis bernama Yuta Okkotsu. Yuta merupakan anak SMA yang kaku dan menjadi korban perundungan. Suatu hari, Rika Orimoto, teman masa kecil Yuta, meninggal karena kecelakaan.Sejak saat itu, Yuta ditempeli roh kutukan perwujudan dari Rika. Kutukan yang diterima Yuta tidak bisa dikendalikan dan sangat kuat. Itu membuat Yuta dan kutukannya mendapatkan perhatian dari para penyihir Jujutsu, termasuk Satoru Gojo.Untuk menyelamatkan Yuta dari kutukan itu, Satoru menawarkan Yuta masuk ke sekolah Jujutsu. Dengan begitu, Satoru jadi bisa memantau dan mengajarkan Yuta untuk mengontrol kekuatannya.Akhirnya Yuta pun setuju untuk masuk ke sekolah Jujutsu.',
        p2: 'Di sana, ia bertemu dengan tiga karakter yang sudah tidak asing lagi bagi para penggemar Jujutsu Kaisen. Ketiganya adalah Inumaki, Panda, dan Maki.Satoru memiliki agenda lain. Bersama para penyihir Jujutsu lainnya, Satoru ingin menguji kekuatan Yuta dan kutukan yang menempel pada dirinya. Apakah Yuta berhasil mengalahkan para penyihir Jujutsu menggunakan kutukannya tersebut?Jujutsu Kaisen 0 merupakan film prekuel dari serial anime Jujutsu Kaisen. Pengumuman film tersebut diumumkan setelah episode finale musim pertama Jujutsu Kaisen, pada Maret 2021.Adapun beberapa pengisi suara untuk Jujutsu 0 adalah Megumi Ogata sebagai Yuta Okkotsu, Kana Hanazawa sebagai Rika Orimoto, Yuichi Nakamura sebagai Satoru Gojo, hingga Takahiro Sakurai sebagai Suguru Geto.Film yang disutradarai oleh Sunghoo Park ini tidak akan memunculkan karakter-karakter yang biasa ditemui di serialnya, seperti Yuji Itadori, Megumi Fushiguro, Nobara Kugisaki, hingga Maki Zenin.'
    },
    {
        poster: './assets/movie15 1.png',
        title: 'Fantastic Beasts: The Secrets of Dumbledore',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '142 Min.',
        producers: 'J. K. Rowling, Steve Kloves, David Heyman, Lionel Wigram, Tim Lewis',
        aired: 'April 13, 2022',
        distributor: '',
        rate: '6.30',
        scores: [6.30],
        genre: ['Fantasy'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Film yang juga dikenal dengan Fantastic Beast 3 ini akan mengawali kisahnya dari Newt Scamander yang menolong qilin. Ini adalah hewan ajaib yang bisa mengetahui ketulusan hati seseorang.Namun dalam proses penyelamatannya, ia dihadang anak buah Grindelwald. Mereka berhasil menghabisi induk qilin dan satu anaknya, sementara kembaran si anak qilin berhasil dibawa Scamander.Inilah yang nantinya akan menjadi misi penyelamatan dunia yang unik dari kejahatan Grindelwald.Albus Dumbledore tak tinggal diam. Ia membentuk pasukan untuk mengamankan qilin. Selain itu, hewan ini nantinya akan dibawa dalam pemilihan kepemimpinan dunia sihir.',
        p2: 'Para anggota dari kelompok Dumbledore terdiri dari saudara Scamander, Theseus, penyihir Amerika yakni Lally, Yusuf Kama, seorang muggle yaitu Jacob Kowalski dan Tina.Dumbledore mempersiapkan beberapa koper untuk anggota tersebut, di mana salah satunya berisi qilin. Kali ini, anda bisa menebak siapa diantara mereka yang membawa hewan ajaib tersebut.Selain dari cerita di Fantastic Beast 3 yang sayang untuk dilewatkan, penonton bakal disuguhkan dengan keajaiban sihir. Bahkan ada salah satu scene yang membawa nostalgia ke Hogwarts.Lantas adakah kemunculan Harry Potter bersama sejumlah kawan-kawannya di sini?'
    },
    {
        poster: './assets/movie16 1.png',
        title: 'Cinderella and the Little Sorcerer',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '86 Min.',
        producers: 'Adam Chiu',
        aired: 'May 6, 2022',
        distributor: '',
        rate: '3.90',
        scores: [3.90],
        genre: ['Fantasy'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Ketika Pangeran Alex (suara Chris Niosi) mengorbankan bentuk manusianya dan berubah menjadi tikus untuk menyelamatkan Ella (suara Geri Courtney-Austein), dia bersumpah untuk melakukan apa pun untuk mematahkan mantra dan membebaskannya. Dengan bantuan dari penyihir magang, Crystal (suara Ashley Bornancin), dan dua teman tikus yang setia, Manny (suara Bob Klein) dan Walter (suara Tony Azzolino), band kecil mulai mencoba mengubah Alex. Ketika mantra Crystal salah, mereka berangkat mencari Penjaga Hutan (suara Nisa Ward) yang dikabarkan memiliki Batu Kehidupan dengan kekuatan pemulihan yang luar biasa.',
        p2: 'Menemukan bahwa Ratu Gurun yang jahat (suara Monica Young) telah mencuri batu itu untuk tujuan jahatnya sendiri, para pahlawan yang tidak terduga berangkat untuk menemukannya. Sementara itu, Olaf (pengisi suara Billy Kametz), seorang pangeran yang licik dan pendendam, mencoba menipu semua orang untuk keuntungan pribadinya. Akankah persahabatan terbukti cukup kuat untuk menaklukkan kekuatan jahat dan akankah Alex mendapatkan kesempatan kedua untuk hidup sebagai manusia?'
    },
    {
        poster: './assets/image 104.png',
        title: 'Top Gun Maverick',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '131 Min.',
        producers: 'Tom Cruise, Jerry Bruckheimer, Christopher McQuarrie, David Ellison, Don Granger',
        aired: 'May 24, 2022',
        distributor: '',
        rate: '8.70',
        scores: [8.70],
        genre: ['Action'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Kapten Pete Maverick Mitchell merupakan salah satu pilot top Angkatan Udara.Setelah lebih dari tiga puluh tahun mengabdi, Maverick merasa bahwa menjadi seorang pilot Angkatan Udara merupakan tempat yang tepat untuknya.Selain itu, Maverick juga merasa dapat melampaui batasan yang tidak mungkin terjadi.Meskipun Maverick merupakan seorang pilot yang top, Ia tidak pernah menginginkan pangkat yang tinggi.Suatu ketika, Laksamana Cyclone direkomendasikan oleh Laksamana Iceman untuk merekrut Kapten Maverick.Nantinya, Kapten Maverick akan melatih detasemen lulusan Top Gun untuk sebuah misi khusus.',
        p2: 'Misi khusus ini belum pernah terjadi sebelumnya.Saat melatih detasemen lulusan Top Gun, Maverick bertemu dengan Letnan Rooster.Letnan Rooster merupakan anak dari Letnan Goose yang tidak lain adalah teman dekat Maverick.Maverick tenggelam dalam ketakutan akan keberhasilan misi ini yang dapat mengorbankan detasemen lulusan Top Gun yang Ia latih.Maverick pun harus menghadapi ketakutannya agar misi khusus tersebut berhasil dan detasemen lulusan Top Gun selamat.Bagaimanakah kelanjutannya?'
    },
    {
        poster: './assets/image 105.png',
        title: 'The Doll 3',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '115 Min.',
        producers: 'Rocky Soraya',
        aired: 'May 26, 2022',
        distributor: '',
        rate: '5.60',
        scores: [5.60],
        genre: ['Horror'],
        country: '',
        language: 'Indonesia',
        rating: 'PG-13',
        p1: 'Film The Doll 3 mengisahkan Tara (Jessica Mila) yang kehilangan kedua orang tuanya karena kecelakaan lalu lintas dan sang adik bernama Gian (Muhammad Zidane) berhasil selamat dari kecelakaan tersebut dan berujung memiliki trauma.Tara telah bertunangan dengan Aryan yang merupakan seorang duda beranak satu. Aryan memiliki seorang anak perempuan bernama Mikha (Montserrat Gizelle) dan keduanya memutuskan untuk menikah dalam waktu dekat.Memiliki trauma pasca kecelakaan yang dialami oleh Gian dan membuat nyawa kedua orang tuanya melayang membuat Gian memutuskan mengakhiri hidupnya dengan bunuh diri.Dan akhirnya Aryan mengundur pernikahannya dengan Tara karena kondisi Tara yang depresi karena kehilangan seluruh anggota keluarganya.',
        p2: 'Tidak berpikir secara jernih membuat Tara mendatangi seorang dukun guna meminta untuk memanggil arwah adiknya bernama Gian yang telah tiada.Dukun pun memanggil arwah adik Tara dan dimasukan ke dalam sebuah boneka yang bernama Bobby.Diisi oleh seorang arwah membuat boneka Bobby hidup layaknya seorang manusia yang bisa bergerak. Adanya arwah Gian di dalam boneka dan hidup berdampingan dengan Tara membuat Kesehatan mental Tara membaik.Namun keadaan itu semua tidak berlangsung lama, Gian tidak menyukai sosok Aryan calon suami kakaknya serta anak Aryan, Mika.Ketidaksukaannya tidak membuat arwah Gian yang berada dalam boneka Bobby selalu berusaha mencelakai Aryan serta Mika.Alasan Gian melakukannya adalah semata-mata ia takut kehilangan kakak kesayangannya setelah menikah dan menjalani kehidupan keluarga bersama Aryan dan anaknya.'
    },
    {
        poster: './assets/TheRoundUp.png',
        title: 'The Round Up',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '106 Min.',
        producers: 'Ma Dong-seok',
        aired: 'June 1, 2022',
        distributor: '',
        rate: '7.40',
        scores: [7.40],
        genre: ['Action'],
        country: '',
        language: 'Korean',
        rating: 'PG-13',
        p1: 'The Roundup mengisahkan tentang perjalanan Ma Dong Seok, seorang detektif kriminal yang memburu para pembunuh buron di Vietnam.Operasi penangkapan buronan ini dimulai ketika 4 tahun setelah dilakukan operasi penyisiran di Garibong-dong.Di mana saat itu detektif Ma Seok Do (Ma Dong Seok) bersama Kapten Jeon Il Man (Choi Gwi Hwa) dan timnya menuju ke Vietnam untuk mengekstradisi tersangka.Tetapi setelah kedatangannya dia menemukan kasus pembunuhan tambahan dan belajar tentang perilaku Kang Hae Sang (Son Seok Koo), yang merupakan seorang pembunuh paling kejam.Kang Hae Sang sempat melakukan pembunuhan terhadap turis selama beberapa tahun demi uang.',
        p2: 'Tapi sayangnya di Vietnam, mereka berdua gagal menangkap Kang Hae Sang dan Kang Hae Sang pun kembali ke Korea.Terlebih di Korea, Kang Hae Sang pernah membunuh putra satu-satunya taipan bisnis di Korea. Kegagalannya tersebut, mereka kembali ke Korea untuk kembali mengejar Kang Hae Sang.Selama pengejaran yang dilakukan Detektif Ma, Kang Hae Sang terus berhasil meloloskan diri dari genggaman polisi dan malah melanjutkan penculikan hingga pembunuhan terhadap warga Korea.Kira-kira apakah Detektif Ma berhasil menangkap Kang Hae Sang dan membawanya ke pengadilan untuk dihukum?'
    },
    {
        poster: './assets/image 106.png',
        title: 'Srimulat: Hil yang Mustahal',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '110 Min.',
        producers: 'Susanti Dewi',
        aired: 'May 19, 2022',
        distributor: '',
        rate: '8.20',
        scores: [8.20],
        genre: ['Comedy'],
        country: '',
        language: 'Indonesia',
        rating: 'PG-13',
        p1: 'Film ini mengisahkan tentang perjalanan karir sebuah grup lawak dari Surakarta bernama Srimulat. Pada mulanya grup lawak ini memulai pertunjukannya di Teater Sriwedari.Tak lama kemudian nama Srimulat mulai terkenal di masyarakat berkat pertunjukkan komedinya tersebut. Di tengah ketenarannya, muncul pemain kendang lucu bernama Gepeng (Bio One) yang mengganggu penampilan mereka.Tepat saat itu, sebuah telegram dari ibu kota datang, berisikan undangan untuk grup lawak Srimulat ini tampil di TV Nasional.Teguh (Rukman Rosadi), selaku ketua Srimulat pun memenuhi undangan tersebut dan Asmuni (Rifnu Wikana) yang diserahi tugas untuk memimpin grup Srimulat menuju Ibukota.Teguh pun akhirnya mengajak Gepeng si pemain kendang lucu itu untuk bergabung dengan grup lawaknya untuk datang ke Ibukota.Di ibukota, Gepeng terpaksa harus beradaptasi dengan para anggota Srimulat yang lain.',
        p2: 'Di tengah keinginannya untuk melebur dengan grup Srimulat, Gepeng dan Basuki (Elang El Gibran) bertemu dengan Royani (Indah Permatasari), anak Babe Makmur (Rano Karno) pemilik kontrakan yang di sewa Srimulat di Ibukota.Bukan hanya kendala harus beradaptasi dengan anggota baru, Srimulat yang terbiasa menggunakan bahasa jawa juga terkendala keterbatasan bahasa Indonesia.Yang dimana karena kendala bahasa ini warga ibu kota tidak bisa menikmati pertunjukkan yang dibawakan oleh grup Srimulat.Di tengah berbagai konflik tersebut, Srimulat mendapatkan permintaan khusus untuk tampil di depan Presiden dan Ibu Negara.'
    },
    {
        poster: './assets/image 107.png',
        title: 'Doraemon: Nobita Little Star Wars',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '109 Min.',
        producers: 'Shin-Ei Animation',
        aired: 'May 25, 2022',
        distributor: '',
        rate: '8.00',
        scores: [8.00],
        genre: ['Fiction', 'Anime'],
        country: '',
        language: 'Japanese',
        rating: 'PG-13',
        p1: 'Alkisah di luar angkasa ada sebuah planet yang ukurannya kecil bernama Pirika, dengan makhluk alien penghuninya yang juga mini. Ketika sedang liburan musim panas, Nobita tidak sengaja mengambil dan membawa roket kecil berisi sosok alien mini dari planet imut tersebut, yang namanya Papi. Papi adalah Presiden Pirika yang sedang berusaha melarikan diri dari planet itu karena diserang oleh para pemberontak. Ia terdampar ke Bumi dan berjumpa Nobita, Doraemon dan teman-teman lainnya. Karena takut menyakiti Papi yang terlalu imut, Doraemon pun mengeluarkan alat canggih bernama ‘Cahaya Senter Pengecil’ yang dapat mengecilkan tubuh mereka.',
        p2: 'Namun tiba-tiba saja muncul sebuah pesawat alien lain yang berbentuk paus dari luar angkasa dan siap menyerang Doraemon juga kawan-kawannya tersebut. Ternyata itu adalah pesawat perang pemberontak yang mengejar Papi hingga ke Bumi. Papi yang tak ingin menyakiti teman-teman barunya di Planet Bumi, lantas berusaha melawan alien yang datang mengejarnya itu dengan sekuat tenaga. Nahas, ia tertangkap dan menjadi sandera lalu dibawa kembali ke Planet Pirika. Tentu Doraemon dan Nobita tak tinggal diam. Mereka kemudian menuju ke Planet Pirika dengan alat canggih milik Doraemon lantas bersama-sama berusaha melepaskan Papi dan seluruh rakyat Pirika yang dalam bahaya.'
    },
    {
        poster: './assets/image 108.png',
        title: 'Anek',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '146 Min.',
        producers: 'Anubhav Sinha, Bhushan Kumar, Krishan Kumar',
        aired: 'May 27, 2022',
        distributor: '',
        rate: '7.40',
        scores: [7.40],
        genre: ['Action'],
        country: '',
        language: 'English',
        rating: 'PG-13',
        p1: 'Anek adalah film thriller aksi politik, di mana Joshua (AK), seorang agen mata-mata yang ganas menjalankan misi untuk menyatukan negara. Film ini menampilkan perjalanan Joshua di wilayah yang dilanda konflik di timur laut di mana ia mencoba untuk mendapatkan kesepakatan damai yang ditandatangani dengan kepala kelompok militan terbesar - Tiger Sangha. Joshua mencoba menyusup ke kelompok separatis dengan berteman dengan salah satu putri anggotanya - Aido.',
        p2: 'Aido adalah seorang petinju yang ganas, yang telah menjadi sasaran rasisme berulang kali tetapi masih bertujuan untuk membawa medali emas untuk India sehingga berharap untuk diterima sepenuhnya sebagai orang India. Akankah Joshua menang dalam misinya untuk menyatukan negara? Ini adalah kisah menyayat hati yang mempertanyakan apa yang diperlukan untuk menjadi orang India di atas semua perbedaan yang dihadapi negara ini.'
    },
    {
        poster: '../assets/image 103.png',
        title: 'The Ancestral',
        director: '',
        writter: '',
        cinematography: '',
        production: '',
        released: '(2022)',
        duration: '100 Min.',
        producers: 'Le-Van Kiet',
        aired: '1 06, 2022',
        distributor: '',
        rate: '4.90',
        scores: [4.90],
        genre: ['Horror'],
        country: 'USA',
        language: 'English',
        rating: 'PG-13',
        p1: 'Film The Ancestral mengisahkan tentang keluarga Vietnam yang pindah ke sebuah rumah berusia ratusan tahun hanya untuk menemukan rahasia mengerikan di bawah tanah.Keluarga tersebut terdiri dari Thanh, seorang duda, dan dua putrinya yang masih remaja. Mereka terpaksa pindah ke rumah yang cukup menyeramkan tersebut karena ada sebuah tragedi keluarga di rumah lamanya. Sesampainya di rumah baru, mereka kemudian memilih kamar masing-masing.Salah satu dari mereka memilih menempati kamar tidur besar yang terlihat indah dan nyaman. Namun, nyatanya semua tidak berjalan dengan lancar.',
        p2: 'Anak terakhir Thanh sering melihat sesuatu yang mengganggu tidurnya. Di rumah baru tersebut, kedua putri Thanh mengalami teror mengerikan setiap malam.Thanh kemudian meminta bantuan dari psikolog lokal untuk mengatasi masalah yang menurutnya hanya masalah psikis saja. Namun, rahasia dan penglihatan yang sangat mengerikan menyadarkan Thanh bahwa masalah di rumah tua itu tidak sesederhana yang ia kira. Kejadian tersebut sangat berbeda dari tragedi yang terjadi di rumah keluarga lama.Thanh menemukan sebuah rahasia besar di ruang bawah tanah rumah tersebut. Lantas, rahasia besar apa yang ditemukan Thanh dan keluarganya?'
    }
];

export {movies};