const anime = [
    {
        poster: './assets/image 37.png',
        title: 'Spy x Family',
        released: '2022',
        duration: '23 Min.',
        type: 'TV', 
        episodes: '24', 
        status: 'Currently Airing', 
        aired: '9 April 2022', 
        premiered: 'Spring 2022',
        producers: 'TV Tokyo, Shogakukan-Shueisha Productions, TOHO animation, Shueisha',
        studios: 'Wit Studio, CloverWorks',
        source: 'Manga',
        licensors: 'None found',
        rating: 'PG-13',
        rate: '0.00',
        scores: [],
        genre: ['Action', 'Comedy', 'Anime'],
        p1: 'Corrupt politicians, frenzied nationalists, and other warmongering forces constantly jeopardize the thin veneer of peace between neighboring countries Ostania and Westalis. In spite of their plots, renowned spy and master of disguise "Twilight" fulfills dangerous missions one after another in the hope that no child will have to experience the horrors of war.',
        p2: 'In the bustling Ostanian city of Berlint, Twilight dons the alias of "Loid Forger," an esteemed psychiatrist. However, his true intention is to gather intelligence on prominent politician Donovan Desmond, who only appears rarely in public at his sons school: the prestigious Eden Academy. Enlisting the help of unmarried city hall clerk Yor Briar to act as his wife and adopting the curious six-year-old orphan Anya as his daughter, Loid enacts his master plan. He will enroll Anya in Eden Academy, where Loid hopes she will excel and give him the opportunity to meet Donovan without arousing suspicion.'
    },
    {
        poster: './assets/image 36.png',
        title: 'Attack on Titan',
        released: '(2013)',
        duration: '24 Min.',
        type: 'TV', 
        episodes: '25', 
        status: 'Finished Airing', 
        aired: 'April 7, 2013 to September 29, 2013', 
        premiered: 'Spring 2022',
        producers: 'Production I.G, Dentsu, Mainichi Broadcasting System, Pony Canyon, Kodansha, Mad Box, Pony Canyon Enterprise',
        studios: 'Wit Studio',
        source: 'Manga',
        licensors: 'Funimation',
        rating: 'R-17+',
        rate: '0.00',
        scores: [],
        genre: ['Action', 'Drama', 'Anime'],
        p1: 'Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure. To ensure their survival, the remnants of humanity began living within defensive barriers, resulting in one hundred years without a single titan encounter. However, that fragile calm is soon shattered when a colossal Titan manages to breach the supposedly impregnable outer wall, reigniting the fight for survival against the man-eating abominations.',
        p2: 'After witnessing a horrific personal loss at the hands of the invading creatures, Eren Yeager dedicates his life to their eradication by enlisting into the Survey Corps, an elite military unit that combats the merciless humanoids outside the protection of the walls. Eren, his adopted sister Mikasa Ackerman, and his childhood friend Armin Arlert join the brutal war against the Titans and race to discover a way of defeating them before the last walls are breached.'
    },
    {
        poster: './assets/movie14 1.png',
        title: 'Jujutsu Kaisen',
        released: '2020',
        duration: '24 Min.',
        type: 'TV', 
        episodes: '24', 
        status: 'Finished Airing', 
        aired: 'October 3, 2020 to March 27, 2021', 
        premiered: 'Fall 2020',
        producers: 'Mainichi Broadcasting System, TOHO animation, Shueisha, dugout, Sumzap',
        studios: 'MAPPA',
        source: 'Manga',
        licensors: 'None found',
        rating: 'R-17+',
        rate: '0.00',
        scores: [],
        genre: ['Action', 'Fantasy', 'Anime'],
        p1: 'Idly indulging in baseless paranormal activities with the Occult Club, high schooler Yuuji Itadori spends his days at either the clubroom or the hospital, where he visits his bedridden grandfather. However, this leisurely lifestyle soon takes a turn for the strange when he unknowingly encounters a cursed item. Triggering a chain of supernatural occurrences, Yuuji finds himself suddenly thrust into the world of Curses—dreadful beings formed from human malice and negativity—after swallowing the said item, revealed to be a finger belonging to the demon Sukuna Ryoumen, the "King of Curses."',
        p2: 'Yuuji experiences first-hand the threat these Curses pose to society as he discovers his own newfound powers. Introduced to the Tokyo Metropolitan Jujutsu Technical High School, he begins to walk down a path from which he cannot return—the path of a Jujutsu sorcerer.'
    }
];

export {anime};